### ISSUE TITLE
These pages are old

### ISSUE THREAD

**Issue by alanmburr** [wackyblackie/sms-launch#2]
I have made some newer versions at <https://www.smslaunch.ml/>.

## TODO
- `<meta>` refresh tags on all pages to link listed above.

**Comment by jaikt** [comment]
That's nice, cuz the old version never allowed the search button, it would be stuck at please enter a `term`

**Comment by alanmburr** [comment]
Really?  It has always worked for me! Can you share a screenshot? That would help me, because the new backend code is based on this repository.

**Comment by jaikt** [comment]
Oops! It suddenly worked now... Also, the website is blocked by the Indian Gov. I used VPN.
